version: "3.8"
services:
  whoamiservice:
    image: traefik/whoami
    command:
      - --name=service

  whoamierror:
    image: traefik/whoami
    command:
      - --name=errorpage

networks:
  default:
    name: traefik-test-network
    external: true
